# Metabolic Pipeline Configuration

# Base directories
base_dir: "/lustre/BIF/nobackup/mulle088"
singularity_dir: "/lustre/BIF/nobackup/mulle088/singularity"
data_dir: "/lustre/BIF/nobackup/mulle088/data_rp/90-1196727703/00_fastq"
media_dir: "/lustre/BIF/nobackup/mulle088/gapseq_pipeline_final/media"
gtdbtk_db: "/lustre/BIF/nobackup/mulle088/gapseq_pipeline_final/gtdbtk_db/release226"
metadata: "input/meta_input_pipeline.csv"

# Output directory
results_dir: "results"

# Trimming parameters
trim_quality: 20
trim_min_length: 50

# SPAdes assembly parameters
spades_kmers: "21,33,55,77"
spades_memory: 120  # GB

# QUAST parameters
min_contig_length: 500

# Binning parameters
concoct_chunk_size: 10000
concoct_min_contig_length: 1000

# CheckM parameters
checkm_lineage: "bacteria"
checkm_completeness_threshold: 50
checkm_contamination_threshold: 10

# GTDB-Tk parameters
gtdbtk_min_perc_aa: 10
gtdbtk_prefix: "bacteria"

# Prodigal parameters
prodigal_mode: "meta"  # Use 'single' for isolate genomes

# Gapseq parameters
gapseq_bitcutoff: 200
gapseq_threads: 1

# Resource allocation
default_threads: 1
assembly_threads: 1
binning_threads: 1
gtdbtk_threads: 8
gapseq_threads: 1

# Memory allocation (MB)
default_mem: 4000
assembly_mem: 120000
binning_mem: 32000
gtdbtk_mem: 64000
gapseq_mem: 16000
