# Optimized Configuration for Maximum Parallelization

# Base directories (unchanged)
base_dir: "/lustre/BIF/nobackup/mulle088"
singularity_dir: "/lustre/BIF/nobackup/mulle088/singularity"
data_dir: "/lustre/BIF/nobackup/mulle088/data_rp/90-1196727703/00_fastq"
media_dir: "/lustre/BIF/nobackup/mulle088/gapseq_pipeline_final/media"
gtdbtk_db: "/lustre/BIF/nobackup/mulle088/gapseq_pipeline_final/gtdbtk_db/release226"
metadata: "/lustre/BIF/nobackup/mulle088/gapseq_pipeline_final/metadata.csv"

# Output directory
results_dir: "results"

# ============================================
# PARALLELIZATION SETTINGS
# ============================================

# Resource Groups (for limiting parallel execution of memory-intensive tasks)
# Uncomment and adjust based on your cluster's capabilities

# Maximum simultaneous assemblies (memory-intensive)
max_assembly_jobs: 20  # Each assembly uses ~120GB RAM

# Maximum simultaneous GTDB-Tk jobs (memory-intensive)
max_gtdbtk_jobs: 5    # Each uses ~64GB RAM

# Maximum simultaneous binning jobs
max_binning_jobs: 20   # Each uses ~32GB RAM

# Maximum simultaneous MAG analyses (lighter weight)
max_mag_analyses: 20  # Each MAG analysis uses ~8-16GB RAM

# ============================================
# TRIMMING SETTINGS
# ============================================
trim_quality: 20
trim_min_length: 50
trim_threads: 4        # Threads per trimming job

# ============================================
# ASSEMBLY SETTINGS
# ============================================
spades_kmers: "21,33,55,77"
spades_threads: 16     # Threads per assembly
spades_memory: 120     # GB per assembly

# ============================================
# BINNING SETTINGS
# ============================================
concoct_threads: 8
concoct_chunk_size: 10000
concoct_min_contig_length: 1000
mapping_threads: 8     # Threads for BWA mapping

# ============================================
# CHECKM SETTINGS
# ============================================
checkm_threads: 8
checkm_lineage: "bacteria"
checkm_completeness_threshold: 50  # Minimum completeness for MAG processing
checkm_contamination_threshold: 10  # Maximum contamination for MAG processing

# ============================================
# PER-MAG ANALYSIS SETTINGS (lighter weight for parallelization)
# ============================================

# GTDB-Tk (per MAG)
gtdbtk_threads_per_mag: 4  # Reduced for better parallelization
gtdbtk_min_perc_aa: 10

# Prodigal (per MAG)
prodigal_mode: "meta"
prodigal_threads: 1  # Prodigal is single-threaded

# Gapseq (per MAG)
gapseq_threads_per_mag: 4  # Reduced for better parallelization
gapseq_bitcutoff: 200

# ============================================
# FASTA SAMPLE SETTINGS (pre-assembled genomes)
# ============================================
# These can use more resources since they don't need binning
gtdbtk_threads_fasta: 8
gapseq_threads_fasta: 8

# ============================================
# CLUSTER RESOURCE ALLOCATION
# ============================================
# Adjust based on your HPC system

# Default resources (for lightweight tasks)
default_threads: 1
default_mem: 4000      # MB
default_time: "02:00:00"

# Heavy tasks
assembly_mem: 120000   # MB
assembly_time: "24:00:00"

binning_mem: 32000     # MB
binning_time: "12:00:00"

gtdbtk_mem: 64000     # MB  
gtdbtk_time: "12:00:00"

checkm_mem: 32000      # MB
checkm_time: "06:00:00"

# Per-MAG tasks (lighter)
mag_analysis_mem: 16000  # MB
mag_analysis_time: "06:00:00"

# ============================================
# SLURM PARTITION SETTINGS
# ============================================
# Adjust based on your cluster's partitions

default_partition: "normal"
highmem_partition: "highmem"  # For assembly, GTDB-Tk
gpu_partition: "gpu"  # If available for certain tools

# ============================================
# OPTIMIZATION FLAGS
# ============================================

# Use local scratch for temporary files (faster I/O)
use_local_scratch: true
scratch_dir: "/scratch/$USER/pipeline_tmp"

# Keep going with independent jobs if one fails
keep_going: true

# Rerun incomplete jobs automatically
rerun_incomplete: true

# Wait time for file system latency
latency_wait: 60
