# Optimized Configuration for Maximum Sample Parallelization
# Run many samples with 1 core each rather than few samples with many cores

# Base directories (unchanged)
base_dir: "/lustre/BIF/nobackup/mulle088"
singularity_dir: "/lustre/BIF/nobackup/mulle088/singularity"
data_dir: "/lustre/BIF/nobackup/mulle088/data_rp/90-1196727703/00_fastq"
media_dir: "/lustre/BIF/nobackup/mulle088/gapseq_pipeline_final/media"
gtdbtk_db: "/lustre/BIF/nobackup/mulle088/gapseq_pipeline_final/gtdbtk_db/release226"
metadata: "input/meta_input_pipeline.csv"

# Output directory
results_dir: "results"

# ============================================
# THREAD ALLOCATION - OPTIMIZED FOR PARALLEL SAMPLES
# ============================================

# Trimming parameters
trim_quality: 20
trim_min_length: 50
trim_threads: 1  # Changed from 4

# SPAdes assembly parameters
spades_kmers: "21,33,55,77"
spades_memory: 120  # GB
spades_threads: 1  # Changed from 16 - MAJOR CHANGE!

# Mapping for binning
mapping_threads: 1  # Changed from 8

# Binning threads
binning_threads: 1  # Changed from 8

# CheckM parameters
checkm_lineage: "bacteria"
checkm_completeness_threshold: 50
checkm_contamination_threshold: 10
checkm_threads: 1  # Changed from 8

# GTDB-Tk parameters (keep high for batch processing)
gtdbtk_min_perc_aa: 10
gtdbtk_prefix: "bacteria"
gtdbtk_threads: 32  # Keep high - only runs once for all samples
gtdbtk_threads_per_mag: 1  # For individual MAGs if needed

# Prodigal parameters
prodigal_mode: "meta"
prodigal_threads: 1  # Already was 1

# Gapseq parameters
gapseq_bitcutoff: 200
gapseq_threads: 1  # Changed from 4-8
gapseq_threads_per_mag: 1  # Changed from 4
gapseq_threads_fasta: 1  # Changed from 8

# QUAST
quast_threads: 1  # Changed from 4

# Resource allocation
default_threads: 1
assembly_threads: 1  # Major change from 16!
binning_threads: 1   # Changed from 8
gtdbtk_threads: 32   # Keep high for batch
gapseq_threads: 1    # Changed

# Memory allocation (MB) - unchanged
default_mem: 4000
assembly_mem: 120000
binning_mem: 32000
gtdbtk_mem: 64000
gapseq_mem: 16000

